apiVersion: apps/v1
kind: Deployment
metadata:
  name: akstodonodejs3
spec:
  selector:
    matchLabels:
      app: akstodonodejs3
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: akstodonodejs3
    spec:
      containers:
        - name: devopstestreg
          image: devopstestreg.azurecr.io/todo-app:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: adsacr-auth

---
apiVersion: v1
kind: Service
metadata:
  name: akstodonodejs3
spec:
  #loadBalancerIP: 13.67.176.224
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: akstodonodejs3
